### PR TITLE
add support for expecting a response

### PR DESCRIPTION
**Pull request by josephdadams**
also supports cycling through serial ports and selecting the first found port if the previously configured port becomes unavailable

### CODE REVIEW

**Comment by josephdadams** [comment]
@istnv would love your feedback on this. Had someone request this feature specifically, as they sometimes have arduinos on serial ports die off and want to know when that happens. Essentially, if the tsp module sends a command to a serial port, it starts an interval, and (if configured to expect a response) no response is received within the allotted time, it throws an error, and, if configured, can send an error response to any tcp connected clients.

**Review by istnv — COMMENTED** [review]
This looks good.
As long as `this.config.response` does not become true when updating from a previous version and `undefined` does not throw an error.

**Comment by josephdadams** [comment]
It shouldn’t but I’ll explicitly check for true which will resolve both concerns. Thanks!

**Comment by istnv** [comment]
I've been surprised too many times assuming it _should_ work. :)

**Pull request merged**
